-- GENERATED by node scripts/build-supabase-activation.mjs. Do not edit this copy.
-- Target reviewed: yopntnzhcfudaabudbld.supabase.co, preflight 2026-10-08 10:13:44 UTC.
-- Read docs/ACTIVACION_2026-10-08.md and review 01_inventory_cutover_preview.sql first.
-- Run ONCE in that project's SQL Editor after preserving a database backup.
-- Converts legacy counts to shared movements without changing available units.
-- Existing reservation shortages become uncounted; never add fictitious stock.
-- Seven missing migrations in ONE transaction; any failure rolls everything back.
-- No seed, customer rewrite, role elevation, RLS disable, external push or data deletion.
-- Execute the WHOLE file, through the END DONAS_APPLY_02_COMPLETE marker.
begin;
set local lock_timeout='5s';
set local statement_timeout='60s';
do $preflight$
declare v_name text; v_signature text;
begin
  foreach v_name in array array['inventory_movements','inventory_revision','push_devices','order_push_jobs',
    'catalog_change_receipts','staff_device_invitations','staff_device_credentials'] loop
    if to_regclass('public.'||v_name) is not null then
      raise exception 'STOP_ALREADY_APPLIED_OR_PARTIAL: %; inspect preflight again, do not repeat this bundle',v_name;
    end if;
  end loop;
  foreach v_name in array array['app_devices','app_user_roles','products','product_variants','orders','order_items',
    'payments','loyalty_accounts','sync_operations','box_purchases','flavor_sales','inventory_manual_counts',
    'inventory_control','inventory_sync_gaps'] loop
    if not exists(select 1 from pg_class where oid=to_regclass('public.'||v_name) and relrowsecurity) then
      raise exception 'STOP_MISSING_PROTECTED_TABLE: %',v_name;
    end if;
  end loop;
  if exists(select 1 from information_schema.columns where table_schema='public'
      and ((table_name='app_devices' and column_name='restored_to_official') or
           (table_name='inventory_manual_counts' and column_name='movement_sequence'))) then
    raise exception 'STOP_PARTIAL_MIGRATION; inspect before applying';
  end if;
  if not exists(select 1 from pg_enum where enumtypid='public.app_role'::regtype and enumlabel='SELLER') then
    raise exception 'STOP_SELLER_MIGRATION_MISSING';
  end if;
  foreach v_signature in array array[
    'public.api_set_manual_inventory(uuid,jsonb)',
    'public.api_push_sync_operations(uuid,uuid,text,text,jsonb)',
    'public.api_transition_order(uuid,public.order_status,uuid,text)',
    'public.api_record_order_payment(uuid,uuid,public.payment_status,uuid,text)',
    'public.api_complete_paid_order(uuid,uuid,public.payment_method)',
    'public.api_create_order_by_customer_id(uuid,uuid,text,text,public.payment_method,text,jsonb)',
    'public.api_pull_orders_for_device(timestamptz,uuid,integer)'] loop
    if to_regprocedure(v_signature) is null then raise exception 'STOP_MISSING_RPC: %',v_signature; end if;
    if has_function_privilege('anon',v_signature,'EXECUTE') or
       has_function_privilege('authenticated',v_signature,'EXECUTE') or
       not has_function_privilege('service_role',v_signature,'EXECUTE') then
      raise exception 'STOP_UNEXPECTED_RPC_PRIVILEGES: %',v_signature;
    end if;
  end loop;
  if to_regprocedure('public.set_updated_at()') is null or
     position('inventory_manual_counts' in pg_get_viewdef('public.inventory_by_flavor'::regclass))=0 or
     position('inventory_movements' in pg_get_viewdef('public.inventory_by_flavor'::regclass))>0 or
     exists(select 1 from public.inventory_by_flavor where purchased_quantity<>0) then
    raise exception 'STOP_UNEXPECTED_INVENTORY_CONTRACT';
  end if;
  if (select count(*) from public.inventory_by_flavor)<>4 then raise exception 'STOP_EXPECTED_FOUR_EXISTING_FLAVORS'; end if;
end; $preflight$;
select pg_advisory_xact_lock(26092601);
-- Transaction-local snapshot: no temporary CREATE TABLE for Studio's auto-RLS rewriter.
select set_config('donas.cutover_before',coalesce((
  select jsonb_agg(jsonb_build_object('variant_id',variant_id,'available_quantity',available_quantity,
    'reserved_quantity',reserved_quantity,'counted',counted)) from public.inventory_by_flavor
),'[]'::jsonb)::text,true);

-- SOURCE 202610030001_shared_inventory.sql / SHA256 a254df9b83d8cd05acb44b1dac41cef68015f5c88316ea3cf01b84c6d6d237d8
-- Preserve today's physical balance; only new ledger rows create movements.
create table public.inventory_movements (
  id bigint generated always as identity primary key,
  variant_id uuid not null references public.product_variants(id),
  quantity_delta bigint not null,
  source_key text not null unique,
  created_at timestamptz not null default clock_timestamp()
);
create table public.inventory_revision (
  id boolean primary key default true check(id),
  revision bigint not null default 0,
  activated_at timestamptz not null default clock_timestamp()
);
insert into public.inventory_revision(id) values(true);
alter table public.inventory_manual_counts add column movement_sequence bigint not null default 0;
-- Remove deliveries already deducted by the previous view before changing it.
update public.inventory_manual_counts c set quantity=greatest(0,c.quantity-coalesce((
  select sum(fs.quantity) from public.flavor_sales fs where fs.variant_id=c.variant_id
  and fs.order_id is not null and fs.reversed_at is null and fs.created_at>c.counted_at),0));
alter table public.inventory_movements enable row level security;
alter table public.inventory_revision enable row level security;
revoke all on public.inventory_movements,public.inventory_revision from public,anon,authenticated;
grant select on public.inventory_movements,public.inventory_revision to service_role;

create function public.inventory_movement_changed() returns trigger
language plpgsql security definer set search_path='' as $$
begin
  perform pg_advisory_xact_lock(26092601);
  update public.inventory_revision set revision=revision+1 where id;
  return new;
end; $$;
create trigger inventory_movement_revision after insert on public.inventory_movements
for each row execute function public.inventory_movement_changed();
create trigger inventory_gap_revision after insert on public.inventory_sync_gaps
for each row execute function public.inventory_movement_changed();

create function public.inventory_flavor_movement() returns trigger
language plpgsql security definer set search_path='' as $$
begin
  perform pg_advisory_xact_lock(26092601);
  if tg_op='INSERT' then
    insert into public.inventory_movements(variant_id,quantity_delta,source_key)
      values(new.variant_id,-new.quantity,'sale:'||new.id) on conflict(source_key) do nothing;
    if new.reversed_at is not null then
      insert into public.inventory_movements(variant_id,quantity_delta,source_key)
        values(new.variant_id,new.quantity,'reverse:'||new.id) on conflict(source_key) do nothing;
    end if;
  elsif old.reversed_at is null and new.reversed_at is not null then
    -- A historical sale excluded at cutover must not add fictitious units.
    if exists(select 1 from public.inventory_movements where source_key='sale:'||new.id) then
      insert into public.inventory_movements(variant_id,quantity_delta,source_key)
        values(new.variant_id,new.quantity,'reverse:'||new.id) on conflict(source_key) do nothing;
    else
      insert into public.inventory_sync_gaps(operation_id) values(new.source_operation_id) on conflict do nothing;
    end if;
  end if;
  return new;
end; $$;
create trigger flavor_shared_stock after insert or update of reversed_at on public.flavor_sales
for each row execute function public.inventory_flavor_movement();

create function public.inventory_box_movement() returns trigger
language plpgsql security definer set search_path='' as $$
declare v_details jsonb; v_item record; v_variant record;
begin
  perform pg_advisory_xact_lock(26092601);
  select payload->'details' into v_details from public.sync_operations where id=new.source_operation_id;
  -- The existing Android box is 12 donuts: 4/4/2/2. Other mixes need reconciliation.
  if coalesce((v_details->>'donutsPerBox')::integer,12)<>12 then
    insert into public.inventory_sync_gaps(operation_id) values(new.source_operation_id) on conflict do nothing;
    return new;
  end if;
  for v_variant in select id,sku from public.product_variants
    where sku in ('DR-CHOCOLATE','DR-VAINILLA','DR-CHOCOLATE-CHISPAS','DR-VAINILLA-CHISPAS') loop
    insert into public.inventory_movements(variant_id,quantity_delta,source_key)
      values(v_variant.id,new.boxes*case when v_variant.sku in ('DR-CHOCOLATE','DR-VAINILLA') then 4 else 2 end,
        'purchase:'||new.id||':'||v_variant.sku) on conflict(source_key) do nothing;
  end loop;
  return new;
end; $$;
create trigger box_shared_stock after insert on public.box_purchases
for each row execute function public.inventory_box_movement();

create or replace view public.inventory_by_flavor with (security_invoker=true) as
select pv.id as variant_id,pv.sku,pv.name,pv.available as offered,
  coalesce(c.quantity,0) as opening_quantity,
  coalesce(m.added,0)::bigint as purchased_quantity,
  coalesce(m.removed,0)::bigint as sold_quantity,
  coalesce(r.quantity,0)::bigint as reserved_quantity,
  greatest(0,coalesce(c.quantity,0)+coalesce(m.added,0)-coalesce(m.removed,0)-coalesce(r.quantity,0))::bigint as available_quantity,
  (c.variant_id is not null and coalesce(c.quantity,0)+coalesce(m.added,0)-coalesce(m.removed,0)>=coalesce(r.quantity,0)
    and c.counted_at>=coalesce((select max(g.created_at)
    from public.inventory_sync_gaps g where g.created_at>(select activated_at from public.inventory_revision where id)),
    '1970-01-01'::timestamptz)) as counted
from public.product_variants pv
left join public.inventory_manual_counts c on c.variant_id=pv.id
left join lateral (
  select sum(greatest(0,quantity_delta)) as added,sum(greatest(0,-quantity_delta)) as removed
  from public.inventory_movements where variant_id=pv.id and id>c.movement_sequence
) m on true
left join lateral (
  select sum(oi.quantity) as quantity from public.order_items oi join public.orders o on o.id=oi.order_id
  where oi.product_variant_id=pv.id and o.status in ('PENDING','ACCEPTED','OUT_FOR_DELIVERY')
) r on true
where pv.sku in ('DR-CHOCOLATE','DR-VAINILLA','DR-CHOCOLATE-CHISPAS','DR-VAINILLA-CHISPAS');

alter function public.api_set_manual_inventory(uuid,jsonb) rename to api_set_manual_inventory_before_shared;
revoke execute on function public.api_set_manual_inventory_before_shared(uuid,jsonb) from service_role;
create function public.api_set_shared_inventory(p_auth_user_id uuid,p_counts jsonb,p_expected_revision bigint default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_result jsonb; v_revision bigint;
begin
  if not exists(select 1 from public.app_user_roles where auth_user_id=p_auth_user_id and role='ADMIN') then
    raise exception 'ADMIN_REQUIRED' using errcode='42501'; end if;
  perform pg_advisory_xact_lock(26092601);
  select revision into v_revision from public.inventory_revision where id;
  if p_expected_revision is not null and p_expected_revision<>v_revision then
    raise exception 'INVENTORY_CONFLICT' using errcode='P0001'; end if;
  v_result:=public.api_set_manual_inventory_before_shared(p_auth_user_id,p_counts);
  update public.inventory_manual_counts set movement_sequence=(select coalesce(max(id),0) from public.inventory_movements);
  update public.inventory_revision set revision=revision+1 where id returning revision into v_revision;
  return v_result||jsonb_build_object('revision',v_revision);
end; $$;
create function public.api_set_manual_inventory(p_auth_user_id uuid,p_counts jsonb) returns jsonb
language sql security definer set search_path='' as $$
  select public.api_set_shared_inventory(p_auth_user_id,p_counts,null);
$$;
revoke execute on function public.api_set_shared_inventory(uuid,jsonb,bigint),public.api_set_manual_inventory(uuid,jsonb)
from public,anon,authenticated;
grant execute on function public.api_set_shared_inventory(uuid,jsonb,bigint),public.api_set_manual_inventory(uuid,jsonb) to service_role;

-- Reservation and cancellation also invalidate an open physical-count form.
create function public.inventory_order_revision() returns trigger
language plpgsql security definer set search_path='' as $$
begin
  perform pg_advisory_xact_lock(26092601);
  update public.inventory_revision set revision=revision+1 where id;
  return new;
end; $$;
create trigger order_inventory_revision after insert or update of status on public.orders
for each row execute function public.inventory_order_revision();
create function public.api_inventory_snapshot() returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_result jsonb;
begin
  perform pg_advisory_xact_lock(26092601);
  select jsonb_build_object('flavors',(select coalesce(jsonb_agg(to_jsonb(i) order by i.sku),'[]')
    from public.inventory_by_flavor i),'revision',r.revision,'serverTime',clock_timestamp(),
    'shared',true) into v_result from public.inventory_revision r where r.id;
  return v_result;
end; $$;
revoke execute on function public.api_inventory_snapshot() from public,anon,authenticated;
grant execute on function public.api_inventory_snapshot() to service_role;
notify pgrst,'reload schema';
-- Include flavor SKU in the mobile cursor so receipts can be reconciled locally.
create or replace function public.api_pull_orders_for_device(p_after_updated_at timestamptz,p_after_id uuid,p_limit integer)
returns table(id uuid,public_code text,status public.order_status,payment_method public.payment_method,
  payment_status public.payment_status,delivery_location text,customer_name text,customer_phone text,
  currency_code text,total_cents integer,created_at timestamptz,updated_at timestamptz,items jsonb)
language sql security definer set search_path='' stable as $$
  select o.id,o.public_code,o.status,o.payment_method,o.payment_status,o.delivery_location,
    o.customer_name_snapshot,o.customer_phone_snapshot,o.currency_code,o.total_cents,o.created_at,o.updated_at,
    coalesce((select jsonb_agg(jsonb_build_object('productVariantId',oi.product_variant_id,
      'productName',oi.product_name_snapshot,'variantName',oi.variant_name_snapshot,'quantity',oi.quantity,
      'sku',oi.sku_snapshot,'unitPriceCents',oi.unit_price_cents,'lineTotalCents',oi.line_total_cents) order by oi.id)
      from public.order_items oi where oi.order_id=o.id),'[]'::jsonb)
  from public.orders o where (o.updated_at,o.id)>(p_after_updated_at,p_after_id)
  order by o.updated_at,o.id limit greatest(1,least(p_limit,100));
$$;


-- SOURCE 202610030002_order_push.sql / SHA256 bba6e389f44101d9ad88ae8fd6770fead599abb7fda3fe2c54400d4fc3ae6da2
create table public.push_devices (
  device_public_id uuid primary key,
  auth_user_id uuid not null references auth.users(id),
  platform text not null check(platform in ('ANDROID','IOS')),
  token text not null unique,
  environment text not null default 'production' check(environment in ('production','sandbox')),
  app_version text not null,
  active boolean not null default true,
  updated_at timestamptz not null default clock_timestamp()
);
create table public.order_push_jobs (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id),
  device_public_id uuid not null references public.push_devices(device_public_id),
  attempts integer not null default 0,
  available_at timestamptz not null default clock_timestamp(),
  delivered_at timestamptz,
  lease_id uuid,
  last_error text,
  unique(order_id,device_public_id)
);
create index order_push_pending on public.order_push_jobs(available_at) where delivered_at is null;
alter table public.push_devices enable row level security;
alter table public.order_push_jobs enable row level security;
revoke all on public.push_devices,public.order_push_jobs from public,anon,authenticated;
grant select on public.push_devices,public.order_push_jobs to service_role;

create function public.api_register_push_device(p_auth_user_id uuid,p_device_public_id uuid,p_platform text,p_token text,p_environment text,p_app_version text)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
  if not exists(select 1 from public.app_user_roles where auth_user_id=p_auth_user_id and role in ('ADMIN','SELLER')) then
    raise exception 'ADMIN_REQUIRED' using errcode='42501'; end if;
  if exists(select 1 from public.push_devices where device_public_id=p_device_public_id and auth_user_id<>p_auth_user_id and active) then
    raise exception 'DEVICE_REVOKED' using errcode='42501'; end if;
  if p_platform not in ('ANDROID','IOS') or length(p_token) not between 32 and 4096
    or p_environment not in ('production','sandbox') then raise exception 'INVALID_OPERATION' using errcode='22023'; end if;
  insert into public.push_devices(device_public_id,auth_user_id,platform,token,environment,app_version)
    values(p_device_public_id,p_auth_user_id,p_platform,p_token,p_environment,p_app_version)
    on conflict(device_public_id) do update set auth_user_id=excluded.auth_user_id,platform=excluded.platform,
      token=excluded.token,environment=excluded.environment,app_version=excluded.app_version,active=true,updated_at=clock_timestamp();
  -- Catch up active pending orders on first registration without replaying history.
  insert into public.order_push_jobs(order_id,device_public_id)
    select id,p_device_public_id from public.orders where status='PENDING'
    on conflict(order_id,device_public_id) do nothing;
  return jsonb_build_object('registered',true);
end; $$;
create function public.api_unregister_push_device(p_auth_user_id uuid,p_device_public_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
  update public.push_devices set active=false,updated_at=clock_timestamp()
    where device_public_id=p_device_public_id and auth_user_id=p_auth_user_id;
  return jsonb_build_object('unregistered',true);
end; $$;
create function public.queue_order_push() returns trigger
language plpgsql security definer set search_path='' as $$
begin
  if new.status='PENDING' then
    insert into public.order_push_jobs(order_id,device_public_id)
      select new.id,d.device_public_id from public.push_devices d
      where d.active and exists(select 1 from public.app_user_roles r where r.auth_user_id=d.auth_user_id and r.role in ('ADMIN','SELLER'))
      on conflict(order_id,device_public_id) do nothing;
  end if;
  return new;
end; $$;
create trigger new_order_push after insert on public.orders for each row execute function public.queue_order_push();

create function public.api_claim_order_push(p_platforms text[]) returns jsonb
language plpgsql security definer set search_path='' as $$
declare v_jobs jsonb;
begin
  with chosen as (
    select j.id from public.order_push_jobs j join public.push_devices d using(device_public_id)
    join public.orders o on o.id=j.order_id
    where j.delivered_at is null and j.attempts<10 and j.available_at<=clock_timestamp()
      and d.active and d.platform=any(p_platforms) and o.status='PENDING'
      and exists(select 1 from public.app_user_roles r where r.auth_user_id=d.auth_user_id and r.role in ('ADMIN','SELLER'))
    order by j.available_at limit 20 for update of j skip locked
  ), claimed as (
    update public.order_push_jobs j set lease_id=gen_random_uuid(),attempts=attempts+1,
      available_at=clock_timestamp()+interval '2 minutes'
      where j.id in (select id from chosen) returning j.*
  ) select coalesce(jsonb_agg(jsonb_build_object('id',j.id,'leaseId',j.lease_id,'orderId',j.order_id,
      'publicCode',o.public_code,'platform',d.platform,'token',d.token,'environment',d.environment)), '[]') into v_jobs
    from claimed j join public.push_devices d using(device_public_id) join public.orders o on o.id=j.order_id;
  return v_jobs;
end; $$;
create function public.api_finish_order_push(p_id uuid,p_lease_id uuid,p_delivered boolean,p_invalid_token boolean,p_error text,p_token text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_device uuid;
begin
  update public.order_push_jobs set delivered_at=case when p_delivered then clock_timestamp() else null end,
    last_error=left(p_error,80),lease_id=null,
    available_at=clock_timestamp()+make_interval(secs=>least(3600,30*(2^least(attempts,6))::integer))
    where id=p_id and lease_id=p_lease_id returning device_public_id into v_device;
  if p_invalid_token and v_device is not null then
    update public.push_devices set active=false where device_public_id=v_device and token=p_token;
  end if;
  return jsonb_build_object('saved',v_device is not null);
end; $$;
revoke execute on function public.api_register_push_device(uuid,uuid,text,text,text,text),public.api_unregister_push_device(uuid,uuid),
  public.api_claim_order_push(text[]),public.api_finish_order_push(uuid,uuid,boolean,boolean,text,text) from public,anon,authenticated;
grant execute on function public.api_register_push_device(uuid,uuid,text,text,text,text),public.api_unregister_push_device(uuid,uuid),
  public.api_claim_order_push(text[]),public.api_finish_order_push(uuid,uuid,boolean,boolean,text,text) to service_role;
notify pgrst,'reload schema';


-- SOURCE 202610050001_inventory_lock_order.sql / SHA256 12a07149ad275a0f39342a71606abef1a8fb56fcc8df7c996f8a3982d9fc99c0
-- All public order writers acquire the inventory lock before locking an order.
-- Payment confirmation updates orders too, including the inventory revision trigger.
alter function public.api_transition_order(uuid,public.order_status,uuid,text)
  rename to api_transition_order_before_lock_order;
revoke execute on function public.api_transition_order_before_lock_order(uuid,public.order_status,uuid,text)
  from public,anon,authenticated,service_role;
create function public.api_transition_order(
  p_order_id uuid,p_to_status public.order_status,p_actor_user_id uuid,p_note text default null
) returns table(id uuid,public_code text,status public.order_status,payment_status public.payment_status,updated_at timestamptz)
language plpgsql security definer set search_path='' as $$
begin
  perform pg_advisory_xact_lock(26092601);
  return query select * from public.api_transition_order_before_lock_order(p_order_id,p_to_status,p_actor_user_id,p_note);
end; $$;

alter function public.api_record_order_payment(uuid,uuid,public.payment_status,uuid,text)
  rename to api_record_order_payment_before_lock_order;
revoke execute on function public.api_record_order_payment_before_lock_order(uuid,uuid,public.payment_status,uuid,text)
  from public,anon,authenticated,service_role;
create function public.api_record_order_payment(
  p_order_id uuid,p_idempotency_key uuid,p_status public.payment_status,
  p_actor_user_id uuid,p_external_reference text default null
) returns table(id uuid,order_id uuid,status public.payment_status,amount_cents integer,currency_code text,confirmed_at timestamptz,replayed boolean)
language plpgsql security definer set search_path='' as $$
begin
  perform pg_advisory_xact_lock(26092601);
  return query select * from public.api_record_order_payment_before_lock_order(
    p_order_id,p_idempotency_key,p_status,p_actor_user_id,p_external_reference);
end; $$;

create or replace function public.api_complete_paid_order(
  p_order_id uuid,p_actor_user_id uuid,p_payment_method public.payment_method
) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_order public.orders%rowtype; v_result record;
begin
  if not exists(select 1 from public.app_user_roles
    where auth_user_id=p_actor_user_id and role in ('ADMIN','SELLER')) then
    raise exception 'STAFF_REQUIRED' using errcode='42501'; end if;
  if p_payment_method is null or p_payment_method not in ('CASH','YAPPY') then
    raise exception 'INVALID_PAYMENT_METHOD' using errcode='22023'; end if;
  perform pg_advisory_xact_lock(26092601);
  perform pg_advisory_xact_lock(hashtextextended(p_order_id::text,0));
  select * into v_order from public.orders where id=p_order_id for update;
  if not found then raise exception 'ORDER_NOT_FOUND' using errcode='P0002'; end if;
  if v_order.status='COMPLETED' and v_order.payment_status='CONFIRMED' then
    return to_jsonb(v_order)||jsonb_build_object('replayed',true); end if;
  if v_order.status<>'OUT_FOR_DELIVERY' then raise exception 'INVALID_TRANSITION' using errcode='P0001'; end if;
  if v_order.payment_status='CONFIRMED' and v_order.payment_method<>p_payment_method then
    raise exception 'PAYMENT_METHOD_CONFLICT' using errcode='P0001'; end if;
  if v_order.payment_status<>'CONFIRMED' then
    update public.orders set payment_method=p_payment_method where id=p_order_id;
    perform public.api_record_order_payment(p_order_id,p_order_id,'CONFIRMED',p_actor_user_id,null);
  end if;
  select * into v_result from public.api_transition_order(p_order_id,'COMPLETED',p_actor_user_id,'Cobrado y entregado');
  return to_jsonb(v_result)||jsonb_build_object('replayed',false);
end; $$;
revoke execute on function public.api_transition_order(uuid,public.order_status,uuid,text),
  public.api_record_order_payment(uuid,uuid,public.payment_status,uuid,text),
  public.api_complete_paid_order(uuid,uuid,public.payment_method) from public,anon,authenticated;
grant execute on function public.api_transition_order(uuid,public.order_status,uuid,text),
  public.api_record_order_payment(uuid,uuid,public.payment_status,uuid,text),
  public.api_complete_paid_order(uuid,uuid,public.payment_method) to service_role;


-- SOURCE 202610050002_mobile_restore_identity.sql / SHA256 f99b351e59c0a9920962cfc60f7cacd13138034da65930823ff420c64f924c59
-- A restored ledger must retain its original sync device, including reversal ownership.
alter table public.app_devices add column restored_to_official boolean not null default false;
create function public.api_restore_device_identity(
  p_auth_user_id uuid,p_client_operation_id uuid,p_server_sequence bigint default null
) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_devices uuid[]; v_device public.app_devices%rowtype;
begin
  if not exists(select 1 from public.app_user_roles where auth_user_id=p_auth_user_id and role='ADMIN') then
    raise exception 'ADMIN_REQUIRED' using errcode='42501'; end if;
  if exists(select 1 from public.sync_operations s join public.app_devices d on d.id=s.device_id
    where s.client_operation_id=p_client_operation_id and d.auth_user_id<>p_auth_user_id) then
    raise exception 'DEVICE_OWNER_CONFLICT' using errcode='42501'; end if;
  select array_agg(distinct d.device_public_id) into v_devices
    from public.sync_operations s join public.app_devices d on d.id=s.device_id
    where s.client_operation_id=p_client_operation_id and d.auth_user_id=p_auth_user_id
      and (p_server_sequence is null or s.server_sequence=p_server_sequence);
  if coalesce(cardinality(v_devices),0)=0 then
    if p_server_sequence is not null then raise exception 'RESTORE_PROOF_NOT_FOUND' using errcode='P0001'; end if;
    return jsonb_build_object('deviceId',null);
  end if;
  if cardinality(v_devices)<>1 then raise exception 'RESTORE_DEVICE_CONFLICT' using errcode='P0001'; end if;
  select * into v_device from public.app_devices where device_public_id=v_devices[1];
  if v_device.status<>'ACTIVE' then raise exception 'DEVICE_REVOKED' using errcode='42501'; end if;
  update public.app_devices set restored_to_official=true where id=v_device.id;
  return jsonb_build_object('deviceId',v_device.device_public_id);
end; $$;
revoke execute on function public.api_restore_device_identity(uuid,uuid,bigint) from public,anon,authenticated;
grant execute on function public.api_restore_device_identity(uuid,uuid,bigint) to service_role;

alter function public.api_push_sync_operations(uuid,uuid,text,text,jsonb) rename to api_push_sync_before_device_ownership;
revoke execute on function public.api_push_sync_before_device_ownership(uuid,uuid,text,text,jsonb) from public,anon,authenticated,service_role;
create function public.api_push_sync_operations(
  p_auth_user_id uuid,p_device_public_id uuid,p_device_name text,p_app_version text,p_operations jsonb
) returns jsonb language plpgsql security definer set search_path='' as $$
begin
  perform pg_advisory_xact_lock(26092601);
  if exists(select 1 from public.app_devices where device_public_id=p_device_public_id and auth_user_id<>p_auth_user_id) then
    raise exception 'DEVICE_OWNER_CONFLICT' using errcode='42501'; end if;
  if exists(select 1 from public.app_devices where device_public_id=p_device_public_id and restored_to_official)
    and p_app_version not like '%-official' then
    raise exception 'DEVICE_MOVED_TO_OFFICIAL' using errcode='P0001'; end if;
  return public.api_push_sync_before_device_ownership(p_auth_user_id,p_device_public_id,p_device_name,p_app_version,p_operations);
end; $$;
revoke execute on function public.api_push_sync_operations(uuid,uuid,text,text,jsonb) from public,anon,authenticated;
grant execute on function public.api_push_sync_operations(uuid,uuid,text,text,jsonb) to service_role;


-- SOURCE 202610070001_catalog_operations.sql / SHA256 5b7fe3e136c33e131f243320b397694a63c58e5291899b2e13d13f78707a6571
-- Existing catalog only; no stock rewriting and no seed data.
-- Studio preflight showed the original variant timestamp trigger missing.
-- Run last among the known update triggers, so generic now() cannot overwrite
-- the monotonic catalog version. Existing rows are not rewritten.
create function public.catalog_updated_at() returns trigger
language plpgsql set search_path='' as $$
begin
  new.updated_at:=greatest(clock_timestamp(),old.updated_at+interval '1 microsecond');
  return new;
end; $$;
revoke execute on function public.catalog_updated_at() from public,anon,authenticated;
create trigger zz_product_variants_catalog_version before update on public.product_variants
for each row execute function public.catalog_updated_at();
create table public.catalog_change_receipts (
  operation_id uuid primary key,
  auth_user_id uuid not null references auth.users(id),
  request_hash text not null check(request_hash ~ '^[0-9a-f]{64}$'),
  result jsonb not null,
  created_at timestamptz not null default clock_timestamp()
);
alter table public.catalog_change_receipts enable row level security;
revoke all on public.catalog_change_receipts from public,anon,authenticated;
create function public.api_update_flavor(p_auth_user_id uuid,p_operation_id uuid,p_request_hash text,
  p_variant_id uuid,p_expected_updated_at timestamptz,p_name text,p_available boolean)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_old public.catalog_change_receipts; v_variant public.product_variants; v_result jsonb;
begin
  if not exists(select 1 from public.app_user_roles where auth_user_id=p_auth_user_id and role='ADMIN') then
    raise exception 'ADMIN_REQUIRED' using errcode='42501'; end if;
  if p_name is null or length(btrim(p_name)) not between 1 and 100 or p_available is null or
    p_expected_updated_at is null or p_request_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'INVALID_OPERATION' using errcode='22023'; end if;
  perform pg_advisory_xact_lock(hashtextextended(p_operation_id::text,18));
  select * into v_old from public.catalog_change_receipts where operation_id=p_operation_id;
  if found then
    if v_old.auth_user_id<>p_auth_user_id or v_old.request_hash<>p_request_hash then
      raise exception 'IDEMPOTENCY_CONFLICT' using errcode='23505'; end if;
    return v_old.result||jsonb_build_object('replayed',true);
  end if;
  perform pg_advisory_xact_lock(26092601);
  select * into v_variant from public.product_variants where id=p_variant_id for update;
  if not found then raise exception 'FLAVOR_NOT_FOUND' using errcode='P0001'; end if;
  if v_variant.updated_at<>p_expected_updated_at then raise exception 'CATALOG_CONFLICT' using errcode='P0001'; end if;
  update public.product_variants set name=btrim(p_name),available=p_available where id=p_variant_id returning * into v_variant;
  v_result:=jsonb_build_object('id',v_variant.id,'name',v_variant.name,'available',v_variant.available,
    'updatedAt',v_variant.updated_at,'replayed',false);
  insert into public.catalog_change_receipts values(p_operation_id,p_auth_user_id,p_request_hash,v_result,clock_timestamp());
  return v_result;
end; $$;
revoke execute on function public.api_update_flavor(uuid,uuid,text,uuid,timestamptz,text,boolean) from public,anon,authenticated;
grant execute on function public.api_update_flavor(uuid,uuid,text,uuid,timestamptz,text,boolean) to service_role;
notify pgrst,'reload schema';


-- SOURCE 202610070002_staff_device_provisioning.sql / SHA256 0a7d89a5b4d7d8ab313a5144f60a6b2b68b162b8931c2bbeae39785c9d23ce0b
create table public.staff_device_invitations (
  token_hash text primary key check(token_hash ~ '^[0-9a-f]{64}$'),
  created_by uuid not null references auth.users(id),
  role text not null check(role in ('ADMIN','SELLER')),
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default clock_timestamp()
);
create table public.staff_device_credentials (
  device_public_id uuid primary key,
  auth_user_id uuid not null references auth.users(id),
  role text not null check(role in ('ADMIN','SELLER')),
  token_hash text not null unique check(token_hash ~ '^[0-9a-f]{64}$'),
  revoked boolean not null default false,
  expires_at timestamptz not null default clock_timestamp()+interval '90 days',
  created_at timestamptz not null default clock_timestamp()
);
alter table public.staff_device_invitations enable row level security;
alter table public.staff_device_credentials enable row level security;
revoke all on public.staff_device_invitations,public.staff_device_credentials from public,anon,authenticated;
grant select on public.staff_device_credentials to service_role;
create function public.api_issue_staff_invitation(p_auth_user_id uuid,p_hash text,p_role text) returns jsonb
language plpgsql security definer set search_path='' as $$
begin
  if not exists(select 1 from public.app_user_roles where auth_user_id=p_auth_user_id and role='ADMIN') then
    raise exception 'ADMIN_REQUIRED' using errcode='42501'; end if;
  insert into public.staff_device_invitations(token_hash,created_by,role,expires_at)
    values(p_hash,p_auth_user_id,p_role,clock_timestamp()+interval '15 minutes');
  return jsonb_build_object('expiresInSeconds',900);
end; $$;
create function public.api_claim_staff_invitation(p_invitation_hash text,p_device_public_id uuid,p_credential_hash text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_invite public.staff_device_invitations;
begin
  select * into v_invite from public.staff_device_invitations where token_hash=p_invitation_hash for update;
  if not found or v_invite.consumed_at is not null or v_invite.expires_at<=clock_timestamp() then
    raise exception 'INVALID_INVITATION' using errcode='42501'; end if;
  if not exists(select 1 from public.app_user_roles where auth_user_id=v_invite.created_by and role='ADMIN') then
    raise exception 'ADMIN_REQUIRED' using errcode='42501'; end if;
  -- A revoked credential can only be replaced with a new administrator-issued invitation.
  insert into public.staff_device_credentials(device_public_id,auth_user_id,role,token_hash)
    values(p_device_public_id,v_invite.created_by,v_invite.role,p_credential_hash)
    on conflict(device_public_id) do update set auth_user_id=excluded.auth_user_id,role=excluded.role,
      token_hash=excluded.token_hash,revoked=false,expires_at=clock_timestamp()+interval '90 days';
  update public.staff_device_invitations set consumed_at=clock_timestamp() where token_hash=p_invitation_hash;
  update public.app_devices set status='ACTIVE' where device_public_id=p_device_public_id and auth_user_id=v_invite.created_by;
  return jsonb_build_object('role',v_invite.role,'userId',v_invite.created_by);
end; $$;
create function public.api_revoke_staff_device(p_auth_user_id uuid,p_device_public_id uuid) returns jsonb
language plpgsql security definer set search_path='' as $$
begin
  if not exists(select 1 from public.app_user_roles where auth_user_id=p_auth_user_id and role='ADMIN') then
    raise exception 'ADMIN_REQUIRED' using errcode='42501'; end if;
  update public.staff_device_credentials set revoked=true where device_public_id=p_device_public_id;
  update public.app_devices set status='REVOKED' where device_public_id=p_device_public_id;
  update public.push_devices set active=false where device_public_id=p_device_public_id;
  return jsonb_build_object('revoked',true);
end; $$;
revoke execute on function public.api_issue_staff_invitation(uuid,text,text),public.api_claim_staff_invitation(text,uuid,text),
  public.api_revoke_staff_device(uuid,uuid) from public,anon,authenticated;
grant execute on function public.api_issue_staff_invitation(uuid,text,text),public.api_claim_staff_invitation(text,uuid,text),
  public.api_revoke_staff_device(uuid,uuid) to service_role;
notify pgrst,'reload schema';


-- SOURCE 202610070003_push_device_revocation.sql / SHA256 8315b0d4b324791f9c8a321c092d40a144c09c0aa10254a43d332af3fc907be9
-- Validate expiry/revocation before claiming FCM jobs; existing authenticated devices still work.
alter function public.api_claim_order_push(text[]) rename to api_claim_order_push_before_staff_devices;
revoke execute on function public.api_claim_order_push_before_staff_devices(text[]) from public,anon,authenticated,service_role;
create function public.api_claim_order_push(p_platforms text[]) returns jsonb
language plpgsql security definer set search_path='' as $$
begin
  update public.push_devices d set active=false
  where d.active and (exists(select 1 from public.staff_device_credentials c where c.device_public_id=d.device_public_id
    and (c.revoked or c.expires_at<=clock_timestamp())) or
    exists(select 1 from public.app_devices a where a.device_public_id=d.device_public_id and a.status='REVOKED'));
  return public.api_claim_order_push_before_staff_devices(p_platforms);
end; $$;
revoke execute on function public.api_claim_order_push(text[]) from public,anon,authenticated;
grant execute on function public.api_claim_order_push(text[]) to service_role;

do $integrity$
begin
  if exists(select 1 from jsonb_to_recordset(current_setting('donas.cutover_before')::jsonb)
    as b(variant_id uuid,available_quantity bigint,reserved_quantity bigint,counted boolean)
    full join public.inventory_by_flavor i on i.variant_id=b.variant_id
    where b.variant_id is null or i.variant_id is null or b.available_quantity<>i.available_quantity or
      b.reserved_quantity<>i.reserved_quantity) then
    raise exception 'STOP_STOCK_DELTA; transaction rolled back';
  end if;
  if not exists(select 1 from pg_trigger where tgrelid='public.product_variants'::regclass
    and tgname='zz_product_variants_catalog_version' and tgenabled='O') then
    raise exception 'STOP_CATALOG_VERSION_TRIGGER_MISSING';
  end if;
end; $integrity$;
notify pgrst,'reload schema';
commit;
select 'APPLIED' as status,'7 migrations; availability and reservations preserved' as verification,
  (select count(*) from public.inventory_by_flavor where not counted) as flavors_requiring_reconciliation,
  (select count(*) from public.order_push_jobs) as push_jobs,
  (select count(*) from public.staff_device_credentials) as authorized_pilot_devices;
-- END DONAS_APPLY_02_COMPLETE
